name: Build and Deploy
on:
  push:

permissions:
  id-token: write
  contents: write
  attestations: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - run: rustup update
    - run: rustup target add wasm32v1-none

    - uses: stellar/stellar-cli@v22.8.1
    - run: stellar contract build --out-dir opt/ --meta source_repo=github:${{ github.repository }}

    - name: Attestation
      uses: actions/attest-build-provenance@v1
      with:
        subject-name: contract
        subject-path: opt/token.wasm

    - name: Upload to Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: hello_world.wasm
        path: opt/token.wasm

    - name: Setup CLI for Testnet
      run: stellar network use testnet

    - name: Setup CLI with Deployer
      run: |
        stellar keys generate deployer --fund
        stellar keys use deployer

    - name: Deploy to Testnet
      run: stellar contract deploy --wasm opt/token.wasm --alias contract

    - name: Check Deployment
      run: stellar contract info build --id contract
